### ISSUE TITLE
Running Sonar Scanner Deletes Previous Solutions

### ISSUE THREAD

**Issue by atbyrd** [SonarSource/sonar-csharp#1182]
### Description

I'm using SonarScanner for MSBuild. It works fine but when I got to the SonarQube server the previosly analyzed projects are no longer available.

### Repro steps

Please provide the steps required to reproduce the problem

**1**. SonarQube.Scanner.MSBuild.exe begin /k:"org.sonarqube:sonarqube-scanner-msbuild" /n:"Enrollments"

**2**. MSBuild.exe /t:Rebuild Enrollments.sln

**3**. SonarQube.Scanner.MSBuild.exe end

### Related information

* SonarC# Version  **7.0**
* Visual Studio Version  **2017(15.5.6)**
* If running through the Scanner for MSBuild, its version  **4.0.2.892**

**Comment by Evangelink** [comment]
Hi @atbyrd,

You are mentioning SonarC# 7.0, as this is an unreleased version I am assuming you are using a local build of master. Could you let me know which commit (sha1)?

Also I am not entirely sure what you mean by

> It works fine but when I got to the SonarQube server the previosly analyzed projects are no longer available.

When you are running the _begin_ step of the scanner for msbuild the content of the .sonarqube folder is cleaned. If this behavior is the one causing you an issue, could you let us know what's the problem with it?

If you are talking about the project page (dashboard) on SonarQube, it is meant to display the latest version of your code so same thing, not sure to understand your problem here.

As I said I am not sure to understand what the problem you are facing so my answer might be wrong/incomplete.

**Comment by atbyrd** [comment]
@Evangelink  My guess is the begin step, cleaning the folder is the problem. I have multiple solutions that I want to analyze. If every time I do an analysis the folder is cleaned I lose everything. Does this have something to do with using the default database?

**Comment by Evangelink** [comment]
@atbyrd Nothing to do with the database.

**Option 1:** If you want to analyze multiple solutions and push the results to the same SonarQube project here is what you can do

```
SonarQube.Scanner.MSBuild.exe begin /k:MultiSolutions
msbuild /t:rebuild Solution1.sln
msbuild /t:rebuild Solution2.sln
msbuild /t:rebuild Solution3.sln
SonarQube.Scanner.MSBuild.exe end
```

**Option 2:** if you want to analyze multiple solutions and push them to different SonarQube projects

```
SonarQube.Scanner.MSBuild.exe begin /k:Solution1
msbuild /t:rebuild Solution1.sln
SonarQube.Scanner.MSBuild.exe end

SonarQube.Scanner.MSBuild.exe begin /k:Solution2
msbuild /t:rebuild Solution2.sln
SonarQube.Scanner.MSBuild.exe end

SonarQube.Scanner.MSBuild.exe begin /k:Solution3
msbuild /t:rebuild Solution3.sln
SonarQube.Scanner.MSBuild.exe end
```

PS: You will need the Scanner for MSBuild 4.0+ for the option 1 to work.

**Comment by Evangelink** [comment]
I am closing this issue (feel free to comment if you think I haven't answered your question).
