### ISSUE TITLE
Determining Which Analyzer is Causing Build Slowness

### ISSUE THREAD

**Issue by johnkoerner** [SonarSource/sonar-csharp#1204]
### Description

I recently enabled the Sonar Analyzers in a .net project and noticed that my build time has increased significantly.  I expected some increase, but my build time went from 6 seconds to 45 seconds for one of my larger projects.

I am looking for a way to determine which analyzers are causing the bulk of the increase of the build time and haven't been able to find any tools that give me that information.

Is there a way to get a breakdown of which analyzers have the biggest impact on my build, so I can determine if we should just turn those off?

### Related information

* Analyzers Nuget Package version 6.8.2.4717
* VS 2017 15.5.6
* Builds are done using Visual Studio

**Comment by valhristov** [comment]
With the next version of SonarLint the analyzers should not affect the performance of your builds in connected mode. You could test the pre-release version, which will be virtually the same as the one we are going to release next week from here:
https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/4.0-RC1

Please, note that you will have to manually disconnect (e.g. revert the commit that was created to connect your project) with SLVS 4.0. We will add automatic connected mode conversion in a future update.

The standalone mode should be ok even with the current version, because it does not add references to the analyzer nuget packages.

**Comment by johnkoerner** [comment]
I wasn't using Sonar Lint in the project, rather just adding the nuget references directly to the analyzers. (Is this not recommended?) We used a shared RuleSet file in the solution to configure the analyzers.  We don't use SonarQube/SonarCloud on the backend to do server side analysis, so there is no connected mode to use.

With my current setup, I am still trying to see if there is a way to determine which of the analyzers has the biggest impact on our performance.

**Comment by valhristov** [comment]
I see. The current connected mode of SonarLint is basically the same as your setup. It is ok to use it like this, but I want to warn you that our nuget packages on nuget.org are something we don't want to support anymore (they are kind of "private" artifacts anyway) and most probably we will stop publishing them very soon. This does not mean that you will not be able to build them from the source code, but it will be a nuisance.

Regarding the performance, here is one relatively old [ticket](https://github.com/SonarSource/sonar-csharp/issues/562) that contains the top slowest rules in the suite at that time. Some of them are already disabled (TokenType, Metrics), others could be disabled, but the overall performance will not change much. In addition, some of the rules are too valuable to be disabled (EmptyNullableValueAccess, NullPointer, etc.).

You can build the current list if you download the source code of this repo, then [build and run the integration tests](https://github.com/SonarSource/sonar-csharp/blob/master/docs/contributing-analyzer.md). After the execution ends (it takes about 10-15min), the performance statistics will be printed on the screen.

**Comment by Corniel** [comment]
@valhristov Can you please deliberate on why you want to drop the SonarLint as (nuget) package? To me, it is the easiest way on enforcing SonarLint rules to be applied by the build (although we also have SonarCube enabled) and ensure that developers see which agreed on rules are violated. Installing the Visual Studio plugin is harder to enforce.

Sorry if this is too much off-topic.

**Comment by valhristov** [comment]
To be fair, we will continue to publish the nugets, but they will not be listed and thus findable.

The main reason for this change is because of the latest changes in SonarLint 4.0 and SonarC# 7.0 the rules in the nugets are not fully configurable through the Visual Studio ruleset files anymore. The user experience is not good and we would like to avoid the confusion for now.

The configuration in SonarLint will come in the near future and will be unified for all SonarSource language analyzers supported in Visual Studio (JavaScript, C++ and soon other languages).

In addition, when you use the rules through SonarLint they will be executed in the background and will not affect the VS build times. It is something our users have been asking for a lot. The downside is that the analysis warnings will not be visible in the Output window anymore (I personally will miss this a lot, as I am heavy user of the Output window).

**Comment by johnkoerner** [comment]
First, I would like to say thanks for the replies  and information, it is very useful.

The way we were using the analyzers were to provide build time warnings. We also enable warnings as errors, so the build fails if there are any analyzer warnings we determine are problematic.  This is nice because it uses the built in tooling in Visual Studio and doesn't require installation of third party components by each developer. 

This reduces friction when ramping up new developers or setting up new build machines for CI. The less we have to install to get a full build setup going, the better.

I would be rather disappointed if the analyzers were not supported going forward as I think that would be a step backward and are one of the biggest benefits to using a solution like this.

**Comment by Corniel** [comment]
I fully agree with @johnkoerner 

I get @valhristov 's point, it is probably easier to ship it that way, but there are users (at least two organisations but I assume more) that prefer the VS-out-of-the-box-analyzer way.

**Comment by valhristov** [comment]
Just a quick update on the nuget releases - we decided to partially revert the changes to the SonarLint connected mode and this affects the analyzers in this project. This means that the nugets will continue to be published to nuget.org.
