### ISSUE TITLE
SonarQube 7.0 - Analyzer result is missing in C# project

### ISSUE THREAD

**Issue by toanvo729** [SonarSource/sonar-csharp#1206]
### Description

We are having an issue with SonarQube 7.0. After build a project in our Prod build server, everything went through except there is no results. Here is the actual warning from the log:

15:19:54.192 WARN: Analyzer working directory does not exist: 'F:\Jazz\Applications\RandoMaker-Prod-SQ\.sonarqube\out\1\output-cs'. Analyzer results won't be loaded from this directory.
15:19:54.348 WARN: Analyzer working directory does not exist: 'F:\Jazz\Applications\RandoMaker-Prod-SQ\.sonarqube\out\0\output-cs'. Analyzer results won't be loaded from this directory.
15:19:54.411 WARN: Property missing: 'sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for this project.
15:19:54.411 WARN: No roslyn issues report not found for this project.

However, everything works fine on our Test build server using SonarQube 6.7. Both are using MS Build Scanner with the same version.

And we noticed that , there is not output-cs folder generated in the Prod Build server.

**Comment by valhristov** [comment]
The fastest way to diagnose this problem is to run the scanner command with `/d:sonar.verbose=true` and msbuild with `/v:diag` and then send us zipped the logs and the .sonarqube from your build machine. It could be of benefit to send logs/folder from both build servers. You could upload it here, that's an upload-only file request on my dropbox:  https://www.dropbox.com/request/CszJAO1ZNXFVl1gwo5hA

**Comment by toanvo729** [comment]
Thank you for following up. I uploaded log files as well as .sonarqube folder and screenshots of both server.

**Comment by valhristov** [comment]
If you search the PROD log file for `Installed SonarQube.Integration.ImportBefore.targets` you will see that the scanner is copying the targets to `c:\Windows\system32\...`. MSBuild does not load the targets files from folders under `c:\Windows\system32` and our code analyzers are not executed. So far the only way to resolve this problem that I am aware of is to change the user your build is running with to a normal domain or local user.

**Comment by toanvo729** [comment]
I changed it to user a local user account to build. Still having the same issue,

11:20:41.615  Installed SonarQube.Integration.ImportBefore.targets to C:\Users\<useraccount>\AppData\Local\Microsoft\MSBuild\15.0\Microsoft.Common.targets\ImportBefore
11:20:41.631  Installed SonarQube.Integration.ImportBefore.targets to C:\Users\<useraccount>\AppData\Local\Microsoft\MSBuild\14.0\Microsoft.Common.targets\ImportBefore

**Comment by valhristov** [comment]
Could you upload the new logs?

**Comment by toanvo729** [comment]
Sure. Re-uploaded with the latest build log. Just fyi, our java application is working fine on both server though.

**Comment by valhristov** [comment]
From the `sonar-project.properties` I see that your projects are nested in each other: `RandoMaker-Prod-SQ\\RandoMaker` contains the console app and the test projects `RandoMaker.Tests` and `RandoMaker.MSTests` are within the same directory. I tested with a similar structure with two projects and I got some warnings like yours for the inner projects in the logs, but the analysis generated issues my SonarQube. The inner test project did not generate issues, but that's expected with the current implementation of SonarC# - it does not report issues for test projects to SonarQube (we will fix that in the future). Do you mind sending me the solution, so that I can properly debug on my side?

**Comment by toanvo729** [comment]
Sorry but I don't understand. RandoMaker-Prood-SQ has the same file structure as Randomaker Test-SQ

**Comment by valhristov** [comment]
If you open `.sonarqube\out\sonar-project.properties` you will find three lines like `C812317D-B72A-4A88-ACB1-202F72A02801.sonar.sources=\`, that contain the full paths of the project contents. The files of `RandoMaker` are in `F:\\Jazz\\Applications\\RandoMaker-Prod-SQ\\`, the files of `RandoMaker.Tests` are in `F:\\Jazz\\Applications\\RandoMaker-Prod-SQ\\RandoMaker.Tests\\` and `RandoMaker.MSTests` files are in `F:\\Jazz\\Applications\\RandoMaker-Prod-SQ\\RandoMaker.MSTests\\`. In other words, the test projects are subfolders of the application folder. I suspect this is the problem, hence I tested with a similarly structured application, but I got results in my SonarQube. I see your project is rather small and that's why I am asking for its source code to be sure I am debugging the real problem.

**Comment by toanvo729** [comment]
Apparently, we just reinstalled msbuild tools and framework SDK 4.7.1 and it worked. Thank you so much for your help

**Comment by valhristov** [comment]
That's good news, don't hesitate to write again if you have questions.

**Comment by dylan-smith** [comment]
@valhristov I see in a couple of issues you've mentioned that it doesn't analyze test projects and you'll be fixing that.  Is that fixed yet?

**Comment by valhristov** [comment]
Nothing done yet, @dylan-smith, but the work to specify the feature has already started. It is a large effort, involving all parts of the Sonar ecosystem - language plugins, scanners and platform (SonarQube). Perhaps we will see the first baby steps towards it in the upcoming months.
