### ISSUE TITLE
Fix S1144: False Positive on Inner Classes

### ISSUE THREAD

**Issue by usmrtester** [SonarSource/sonar-csharp#1225]
Please see closed ticket #1026.  Please re-open this ticket or create another.  Attached is a better example of this false positive.  Notice in the attached pic and sample code that there's 1 reference to OtherInnerClass, its grayed out and it's throwing up the S1144 message.

Code:
[TestClass.zip](https://github.com/SonarSource/sonar-csharp/files/1798756/TestClass.zip)

Pic:
![s1144falsepositive](https://user-images.githubusercontent.com/32103332/37234630-936d1ea6-23be-11e8-91e0-c10e0f50560c.png)

* SonarC# Version - 3.10.0.3095
* Visual Studio Version - 2017, 15.6.1

**Comment by michalb-sonar** [comment]
Thanks for the code sample @usmrtester. I am able to reproduce the issue even if `OtherInnerClass` is `internal`.

**Comment by valhristov** [comment]
I guess the rule does not take into account "arrow" method bodies when looking for references.

**Comment by usmrtester** [comment]
This has nothing to do with "arrow" methods.  You can revise this code to not use "arrow" methods and still get the false positive.

**Comment by usmrtester** [comment]
Here's another example with no "arrow" methods.  Also, see original ticket which has no arrow methods.

![s1144withnoarrowmethods](https://user-images.githubusercontent.com/32103332/37351752-c6087c0a-26a9-11e8-9d8d-4240b147b05e.PNG)

**Comment by rliberoff** [comment]
Hi,

I'm having a similar issue. This is my example code:

`
private sealed class DummyOriginalCallerExecutionContextAttribute : Attribute
{
}

[DummyOriginalCallerExecutionContext]
private class FakeController : Controller
{
}
`

The previous code (some parts removed due to non-disclosure agreements) belongs to a unit test, where the DummyOriginalCallerExecutionContextAttribute is indicated as an offending S1144, but it is being clearly used as an attribute by the FakeController class.
