### ISSUE TITLE
Rule S3900: Arguments of public methods should be validated against null

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-csharp#164]
Implements [RSPEC-3900 Arguments of public methods should be validated against null](https://jira.sonarsource.com/browse/RSPEC-3900)

Contributes to [MMF-963](https://jira.sonarsource.com/browse/MMF-963)

**Comment by Evangelink** [comment]
We need to discuss this rule because
- if we decide to create a new rule we might have a lot of FP when developers will use third-party/helpers to handle the check to null.
- if we decide to improve the detection of possible null dereference on the SE engine then we will probably also have a lot of FP because we don't have cross-file support.
