### ISSUE TITLE
sonar-charp version question

### ISSUE THREAD

**Issue by Hilalem** [SonarSource/sonar-csharp#1821]
Hi this is not an issue, just a question, with which release of sonar-csharp  did sonar start to need to build the project ?
Thank you

**Comment by valhristov** [comment]
If I am not terribly wrong, SonarC# requires project rebuild since version 4.0. At that point it started integrating into the C# compiler (Roslyn) which executes the SonarC# analyzers at compile time, hence the need to build the project. SonarC# supports the C# compiler that comes with Visual Studio 2015 Update 3 and later.

**Comment by Evangelink** [comment]
Hi @Hilalem,

I am closing this thread. Please feel free to re-open or to comment if there was still something unclear to you.

Cheers,
Amaury
