### ISSUE TITLE
Rule S4529: Exposing HTTP endpoints is security-sensitive

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#1991]
[RSPEC-4529](https://jira.sonarsource.com/browse/RSPEC-4529)

Exposing HTTP endpoints is security-sensitive. It has led in the past to the following vulnerabilities:

**Comment by PeterRockstars** [comment]
@valhristov We are seeing this pop up in SonarCloud, but not in Visual Studio, any idea why that is?

**Comment by Evangelink** [comment]
@PeterRockstars The hotspot rules are not displayed in SonarLint because they are a special kind of rules that might generate more FPs and so lower having a good experience inside the IDE.

**Comment by PeterRockstars** [comment]
That makes sense, thanks. Our build server is logging those errors during the build however, and if I run the same dotnet build command on my machine, the warnings are not logged. Is that because of something the "Prepare Sonar Analysis" step does?

**Comment by vishnu2017** [comment]
Any Update on this issue. @PeterRockstars ?

**Comment by duncanp-sonar** [comment]
FYI the hotspot rules are only executed when an analysis is being run and the results pushed to SonarQube/Cloud.
For local builds, this happens when you execute the SonarScanner for MSBuild `begin` step before running MSBuild. For Azure Pipeline builds, it happens when the `Prepare Sonar Analysis` step is executed before the MSBuild step.

@vishnu2017 if you have an issue/question about using the scanner, please start a thread on the [community forum](https://community.sonarsource.com/c/help).
