### ISSUE TITLE
S1206 detects false positives if using a comparable base class.

### ISSUE THREAD

**Issue by Portikus** [SonarSource/sonar-csharp#240]
Hi,

I attached a small repo solution for the issue i am going to descripe [ComparableBug.zip](https://github.com/SonarSource/sonar-csharp/files/955002/ComparableBug.zip)
I recently added a abstract base class for my classes which implementing the `IComparable<T>` interface.
So that the only methods each sub class has to override only the method `int CompareTo(T other)` and  `int GetHashCode()`. 
The base class provides a implementation for 'bool Equals(T other)' and ` bool Equals(object obj)`.

This means the sub class has Equals overridden and so the warning is wrong.

**Comment by Evangelink** [comment]
Hi @Portikus ,

This is actually not a FP (even if this might be under some circumstances). As you probably know `GetHashCode` and `Equals` methods have to be equivalent, meaning that if A == B then A.GetHashCode() == B.GetHashCode(). In your example, the base class defines the `Equals` method but let the sub-class defining the `GetHashCode` meaning that a sub-class could have a different hashcode than equality.
Based on your needs I would recommend to either have the base class defining the `GetHashCode` and `Equals` or to also make the `Equals` abstract so that all sub-class needs to define the equality and the hashcode.

Does it make sense for you?

Also, having a quick look at your class I have spotted an infinite loop in the definition of your equality. The `==` calls the `.Equals` which in turn calls the `==`. Finally, this is pretty weird to define the `Equals` method (intended to be a value equality) as a reference equality (that's the purpose of the default `==`).

**Comment by Portikus** [comment]
Hi @Evangelink 
thank you for your answer. Yes I detected the infinite loop right after this post :D.
Yes I guess this makes sense. I will let the sub class also define Equals. 
Thank you again.

**Comment by Evangelink** [comment]
You are welcome!
