### ISSUE TITLE
Rule S4004: Collection properties should be readonly

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#280]
[RSPEC-4004](https://jira.sonarsource.com/browse/RSPEC-4004)

A writable collection property can be replaced by a completely different collection. Making it readonly prevents that while still allowing individual members to be set. If you want to allow the replacement of the whole collection the recommended pattern is to implement a method to remove all the elements (e.g. `System.Collections.ArrayList.Clear`) and a method to populate the collection (e.g. `System.Collections.ArrayList.AddRange`).

**Comment by jmevel** [comment]
Hi, I'm coming here after getting an issue with Sonar rules.

The problem with this rule is that it goes in "conflict" with [S3956](https://github.com/SonarSource/sonar-dotnet/issues/506).
We, therefore can't use `AddRange` because it is not available for `IList`.

Are we supposed to re-implement our own `AddRange` extension method or is there another simpler way?
I don't really want to reinvent the wheel...

Thanks for your answer
