### ISSUE TITLE
Fix S2930: Should report on all classes implementing IDisposable

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-csharp#326]
[RSPEC-2930](https://jira.sonarsource.com/browse/RSPEC-2930) "IDisposable should be disposed" has artificial limitation to report issues only on certain classes, which should be removed.

Coming from [SONARCS-840](https://jira.sonarsource.com/browse/SONARCS-840)

**Comment by JasonBock** [comment]
This is a huge "miss" in my mind. I just tried using SonarAnalyzer.CSharp, and I was surprised that it missed an occurrence of this in my test code. Then I saw that it has the S2930 analyzer, but....it's limited to certain types? I'm curious, is it stated anywhere which types? And why is it limited?

**Comment by valhristov** [comment]
@JasonBock thanks for the feedback! A couple of years ago the rule covered all types that implement `IDisposable`, but was changed to trigger only on specific types. I cannot find exactly why, but I guess it was because of too many raised false positives... We agree that the value of this rule is not very high in its current state, hence we have this ticket for improvement.

**Comment by michalb-sonar** [comment]
@JasonBock The suggestion sounds very sensible. However, once implemented, this rule generates a lot of noise. That is particularly bad, because the reported issues are classified as blocker bugs, therefore our bar for quality is very high.
There are few cases where we could raise a code smell/minor bug, but at the moment there are no facilities for rule to raise items at different severity/clarification. That would require creating a separate rule, which we debated but rejected because it would be confusing and relatively low value.
