### ISSUE TITLE
Tuple literals make the analysis fail

### ISSUE THREAD

**Issue by markvincze** [SonarSource/sonar-csharp#391]
### Description

Using tuple literals can cause the following exception to be thrown at the end of the sonar-scanner analysis: `lang.IllegalArgumentException: Start pointer [line=11, lineOffset=18] should be before end pointer [line=11, lineOffset=18]`

### Repro steps

Execute code analysis on a source file containing this method declaration.

```
public interface IFoo
{
    Task<(Bar bar, string str)> Baz(Guid id);
}
```

### Expected behavior

The analysis should succeed without an error.

### Actual behavior

The following error is printed by `sonar-scanner`.

```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalArgumentException: Start pointer [line=11, lineOffset=18] should be before end pointer [line=11, lineOffset=18]
        at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.newRangeValidPointers(DefaultInputFile.java:265)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:203)
        at org.sonarsource.dotnet.shared.plugins.SensorContextUtils.toTextRange(SensorContextUtils.java:41)
        at org.sonarsource.dotnet.shared.plugins.protobuf.SymbolRefsImporter.consumeFor(SymbolRefsImporter.java:47)
        at org.sonarsource.dotnet.shared.plugins.protobuf.SymbolRefsImporter.consumeFor(SymbolRefsImporter.java:33)
        at org.sonarsource.dotnet.shared.plugins.protobuf.ProtobufImporter.consume(ProtobufImporter.java:50)
        at org.sonarsource.dotnet.shared.plugins.protobuf.RawProtobufImporter.accept(RawProtobufImporter.java:44)
        at org.sonarsource.dotnet.shared.plugins.AbstractSensor.parseProtobuf(AbstractSensor.java:90)
        at org.sonarsource.dotnet.shared.plugins.AbstractSensor.importResults(AbstractSensor.java:83)
        at org.sonar.plugins.csharp.CSharpSensor.executeInternal(CSharpSensor.java:119)
        at org.sonar.plugins.csharp.CSharpSensor.execute(CSharpSensor.java:79)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

### Known workarounds

None

### Related information

* SonarC# Version: 5.10.1.1411
* Visual Studio Version: 2017
* If running through the Scanner for MSBuild, its version: 3.0.3.778

**Comment by valhristov** [comment]
Hi @markvincze,

I could not reproduce the problem with a simple application, containing only the IFoo interface you mentioned and an empty class named Bar. Since the stack trace you sent is usually related to another problem we are having - with the source files encoding, I suspect it might be the reason for the exception. Can you check if all files in the project have UTF8 encoding?

Thanks,
.Net team

**Comment by markvincze** [comment]
Hi @valhristov,

I tried now a very isolated test, I created a file with the following content:

```
using System.Threading.Tasks;

public interface IFoo
{
    Task<(string bar, int baz)> Qux();
    //void Qux();
}
```

This is my `sonar-scanner.properties`:

```
sonar.host.url=https://our-sonar-server
sonar.projectKey=SonarTest
sonar.projectName=SonarTest
sonar.sources=C:/Temp/SonarTest.cs
```

And if I execute `sonar-scanner-3.0.3.778-windows\bin\sonar-scanner.bat`, I get the same exception. I uploaded the complete output to [here](https://gist.github.com/markvincze/e52b2ba788913433fd51bfc376c53f32).

If I comment out the first `Qux` declaration and uncomment the second one, then the analysis is successful.

I tried opening the source file in Sublime Text, and explicitly save it with UTF-8, but I get the same error.
I uploaded the actual file to [here](https://drive.google.com/file/d/0B6pvt-_8yHpNT0RQTnpVZ212ZVU/view?usp=sharing)

One thing I noticed in the output is this line:

```
INFO: Default locale: "en_US", source code encoding: "windows-1252" (analysis is platform dependent)
```

Can this be the issue?

**Comment by janos-ss** [comment]
Hi @markvincze 

I can reproduce your issue if I analyze using the Scanner for CLI, but we don't support this way of using SonarC#.

The recommended way of using SonarC# is documented on the [plugin's homepage](https://docs.sonarqube.org/pages/viewpage.action?pageId=1441900). In a nutshell, it requires Scanner for MSBuild, which consists of 3 steps: begin, build, end.

Note that when you migrate to using Scanner for MSBuild as recommended, you will not need a scanner properties file at all (it will be ignored). Scanner for MSBuild automatically creates the correct configuration based on your `.sln` and `.csproj` files.

**Comment by markvincze** [comment]
@janos-ss,

Thanks for the info!
Do I understand correctly that I will not be able to use the Scanner for MSBuild with the `dotnet` CLI in a .NET Core project until [SONARMSBRU-310](https://jira.sonarsource.com/browse/SONARMSBRU-310) is done?

**Comment by janos-ss** [comment]
@markvincze yes that is correct.

**Comment by rducom** [comment]
Hello,

We also have this issue, on net461, using the "standard" way to launch the runner :

`SonarQube.Scanner.MSBuild.exe begin /d:"sonar.login=****" /d:"sonar.analysis.mode=publish" /k:"XXXX" /d:"sonar.host.url=http://sonar.XXXX.fr"  /d:sonar.language=cs /d:sonar.sources=Application/,Data/,Domain/,XXXX/,Infra/,Web/ /d:sonar.exclusions=**/Static/**/*,**/SPA/**/*  /d:sonar.cs.opencover.reportsPaths="opencoverCoverage.xml" /d:"sonar.branch=MyBranch" `

On some methods returning tuples in C#7 syntax (not all methods returning tuples), we have the following error :

```
[backend] java.lang.IllegalArgumentException: Start pointer [line=147, lineOffset=26] should be before end pointer [line=147, lineOffset=26]
[backend] 	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[backend] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRangeValidPointers(DefaultInputFile.java:265)
[backend] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:203)
[backend] 	at org.sonarsource.dotnet.shared.plugins.SensorContextUtils.toTextRange(SensorContextUtils.java:41)
[backend] 	at org.sonarsource.dotnet.shared.plugins.protobuf.SymbolRefsImporter.consumeFor(SymbolRefsImporter.java:47)
[backend] 	at org.sonarsource.dotnet.shared.plugins.protobuf.SymbolRefsImporter.consumeFor(SymbolRefsImporter.java:33)
[backend] 	at org.sonarsource.dotnet.shared.plugins.protobuf.ProtobufImporter.consume(ProtobufImporter.java:50)
[backend] 	at org.sonarsource.dotnet.shared.plugins.protobuf.RawProtobufImporter.accept(RawProtobufImporter.java:44)
[backend] 	at org.sonarsource.dotnet.shared.plugins.AbstractSensor.parseProtobuf(AbstractSensor.java:90)
[backend] 	at org.sonarsource.dotnet.shared.plugins.AbstractSensor.importResults(AbstractSensor.java:83)
[backend] 	at org.sonar.plugins.csharp.CSharpSensor.executeInternal(CSharpSensor.java:119)
[backend] 	at org.sonar.plugins.csharp.CSharpSensor.execute(CSharpSensor.java:79)
[backend] 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
[backend] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
[backend] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
[backend] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
[backend] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
[backend] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[backend] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[backend] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
[backend] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
[backend] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:255)
[backend] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
[backend] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[backend] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[backend] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
[backend] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[backend] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[backend] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[backend] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
[backend] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
[backend] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
[backend] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[backend] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[backend] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[backend] 	at java.lang.reflect.Method.invoke(Unknown Source)
[backend] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[backend] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[backend] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
[backend] 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
[backend] 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
[backend] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
[backend] 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
[backend] ERROR: 
[backend] ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
[backend] The SonarQube Scanner did not complete successfully
```

This is blocking our CI pipeline, so it's really a big problem right now.
We don't have a repro sample project, this issue is randomly happening.
The only workaround right now is refactoring code to replace Tuples with concretes types....

This issue should be reopened

**Comment by janos-ss** [comment]
@rducom Since you get the same failure due to invalid text range, I reopen this, thanks for reporting.

I have a question about this part:

> On some methods returning tuples in C#7 syntax (not all methods returning tuples), we have the following error : [...]
>
> [...] this issue is randomly happening.

Do I understand correctly that for some method X returning tuples in C#7 syntax, you sometimes get a failure sometimes not? Or do you consistently get failure for the same method X? Please confirm, thanks.

**Comment by rducom** [comment]
For some methods, there is a failure, for others there isn't.
But once there is a failure on a specific file/method, the failure happens each time on this file/method.

It's really hard to find the specific file causing the issue : the sonar runner post-process step is running over big file batches (about 400~500 files in a batch.). Even in "verbose" mode, we don't have the filename on the exception stacktrace...

However, here are some diffs, as example for what I fixed last week, in order to show you the kind of code causing the issue :

```
-		private static (int? id, string firstName, string lastName) GetUser(LeaveUser user)
+		private static Approver GetUser(LeaveUser user)

-		public virtual (int? id, string firstName, string lastName) GetManager(int nbApprovals, IApprovable approvable)
+		public virtual Approver GetManager(int nbApprovals, IApprovable approvable)

-		helper.Setup(h => h.GetManager(2, lr)).Returns(null);
+		helper.Setup(h => h.GetManager(2, lr)).Returns((Approver)null);
```

**Comment by markvincze** [comment]
Hi @rducom,

The way I found the guilty file was to keep changing `/d:sonar.sources` and set it to smaller and smaller parts of my repository until I found a single file that was causing the issue.  
For now, I worked around the problem by adding these files to `/d:sonar.exclusions`. For me, this was fine since I had tuples like this only in 2 files, but if you have it all over the place, then, of course, this is not an alternative.

**Comment by markvincze** [comment]
Btw. on a different note, @janos-ss you mention

>I can reproduce your issue if I analyze using the Scanner for CLI, but we don't support this way of using SonarC#

Shouldn't then the Scanner CLI fail and print a descriptive error message saying that this way of using SonarC# is not supported?  
Because we've been using this method of analysis for all of our .NET Core projects and the analysis have always run without any errors (except this issue with the tuples) and produced seemingly meaningful results.

But the fact that this is not supported means that all of our analysis results might have been completely incorrect?

**Comment by rducom** [comment]
Hi @janos-ss 

FYI, yesterday, we have had this issue on C#7 tuples inside function bodies. So this issues don't only applies to tuple return types, but also to other cases. The code involved yesterday was like this one :

`
ILookup<(DateTime, bool), Warning> indexedWarnings = warnings.ToLookup(i => (i.Date, i.IsError));`

And then, using the Contains lookup method, and indexers.

Interestingly, this code is on our codebase since 3 weeks, and it's the first time sonar runner crashed on this part. So it's really difficult to reproduce this issue.

**Comment by jjafuller** [comment]
I've notice issues with sonarlint not catching rules violations, and I think it may be related to this underlying issue.

**Comment by rducom** [comment]
No updates on this blocker bug since June. 
Is this issue the right place for reporting ? 
Can someone point to the right place to report if known ? (msbuild-runner ? internal sonarsource's Jira ?)

**Comment by valhristov** [comment]
Hi @rducom we are working on C#7 support right now and this fix should come for free in the coming updates.

**Comment by rducom** [comment]
Thanks for the update @valhristov !

**Comment by duncanp-sonar** [comment]
Hi @rducom,

I haven't managed to repro this bug using the Scanner for MSBuild. I've tried the same file encoding, same C# plugin version, sample file provided above, various versions of the SonarQube Scanner for MSBuild, and various versions of the SonarQube server.

Are you still encountering the issue? If so, please confirm the versions you are using of the following (you might have upgraded since then the issue was first reported, and it would be useful to know if the issue appears in multiple versions):

* Scanner for MSBuild, C# plugin, SonarQube server.
* version (including service pack) of Visual Studio installed on CI machine

From the logs it looks like the issue is with the .\.sonarqube\out\symref.pb file that is being processed. If you could provide that file it would useful (FYI the file contains list of file names and locations of symbols within that file. It's used for code highlighting on the server. It doesn't contain any code).

Thanks.

**Comment by rducom** [comment]
Hi @duncanp-sonar

I'm sorry, since this issue have been blocking our ci-pipeline, we have forbidden the new tuple syntaxes usage, and we will not be able to try to reintroduce it if this issue is not fixed...

As I said previously, it's not easy to reproduce since the same code could or couldn't trigger this crash, the case depends on external parameters (other lines modified)... Making this issue really weird... 

But I still have hopes it can be fixed :)

**Comment by duncanp-sonar** [comment]
Ok, thanks @rducom. We'd like it to be fixed too, but at the moment we don't know where the problem is :) Unfortunately, @janos-ss is can no longer repro the bug even using the Scanner CLI.

If anyone else is able to repro this bug, we'd be grateful if you could let us know  Thanks.
