### ISSUE TITLE
Update of plugin to v6.0 doesn't report any issues in code anymore

### ISSUE THREAD

**Issue by dragan-stepanovic** [SonarSource/sonar-csharp#488]
[v5.11.txt](https://github.com/SonarSource/sonar-csharp/files/1108456/v5.11.txt)
[v6.0.txt](https://github.com/SonarSource/sonar-csharp/files/1108457/v6.0.txt)

### Description

We're using SonarQube 	v6.4.0.25310 and triggering SonarQube analysis from TeamCity's SonarQube plugin. As I can see from the logs, files are indexed (84 of them exactly), but there are no issues reported anymore in SonarQube.
The only thing I've done between these two points in time is updating sonar csharp plugin from v5.11 to v6.0.

### Repro steps

1.Install latest SonarQube
2.Run analysis on a simple project and verify that the issues are reported
3. Update CSharp SonarQube plugin to newest version (6.0)
4. Run the analysis again and notice that no more issues are reported

### Expected behavior

Issues in c# code are still reported after updating plugin.

### Actual behavior

Issues are still reported.

### Known workarounds

Reinstalling SonarQube perhaps and thus reverting version of C# plugin to earlier version perhaps?

### Related information
I've attached log when I was running analysis with plugin v5.11 and with newest, v6.0

* SonarC# Version - v6.0
* VS2017
* If running through the Scanner for MSBuild, its version

**Comment by Evangelink** [comment]
Hi @dragan-stepanovic ,

The message is indeed confusing.
SonarC# 6.0 dropped the support for MsBuild 12 and has a few API breaking changes (hence the major version bump) and requires Scanner for MsBuild 3.0+.

If you can't update the version of the Scanner you will have to stick with the previous version.

**Comment by dragan-stepanovic** [comment]
How do you revert the version of the plugin?

**Comment by valhristov** [comment]
Hi @dragan-stepanovic, 

You will need to manually install the old version of the SonarC# plugin. Please see the last section - Manual Updates in the [documentation](https://docs.sonarqube.org/display/SONAR/Update+Center#UpdateCenter-ManualUpdates), for instructions how to do it.

It is as simple as downloading the jar file and copying it into a specific subfolder in the SonarQube installation directory.

Since we are receiving many reports for this problem and we are also not in charge of some plugins (e.g. the TeamCity plugin), we are planning to release an update of SonarC# that will fix the incompatibility. I cannot promise a specific date, though.
