### ISSUE TITLE
Invalid S1144 on ctor

### ISSUE THREAD

**Issue by sm-g** [SonarSource/sonar-csharp#520]
### Repro steps

    public class Service
    {
        public Service(IOAuthService oAuthService)
        {

        }
        public virtual void Do()
        {

        }
    }
    public class Tests
    {
        [Test]
        public void Foo()
        {
            ...
        }
        private class ServiceMock : Service
        {
            public ServiceMock(IOAuthService oAuthService)
                : base(oAuthService)
            {
            }

            public override void Do()
            {
            }
        }
    }

### Expected behavior

No S1144

### Actual behavior

S1144 on `public ServiceMock(IOAuthService oAuthService) : base(oAuthService) {}`

### Related information

* SonarC# Version 6.0.0.2033
* Visual Studio Version 2017

**Comment by valhristov** [comment]
Hi @sm-g, 

Are you explicitly instantiating the ServiceMock class in the Foo() method? E.g. using `new ServiceMock(something)`. It is possible S1144 to raise false positive for classes that are instantiated through a DI container because it is somehow hidden. I wasn't able to reproduce the problem with the provided code snippet and I would greatly appreciate more information about how to do it.

Thanks in advance,
Valeri

**Comment by sm-g** [comment]
Yes, it is instantiated through a DI. 

Notice that there is no other ctors in `ServiceMock` and after removing code not compiles, because default cotr cannot be used.

**Comment by valhristov** [comment]
You can prevent the rule from raising issues if you make the class public... We have no means of knowing if a class is instantiated if a DI container is used.
