### ISSUE TITLE
DotCoverReportParser fails to parse html-reports generated by dotCover

### ISSUE THREAD

**Issue by ESolovova** [SonarSource/sonar-csharp#787]
### Description

As far as I can see from the source code the regular expression used by DotCoverReportParser for parsing reports doesn't correspond to the actual dotCover html-reports format, which leads to the following exception:

![sonar_plugin_exception](https://user-images.githubusercontent.com/17826751/30541391-e8c85de2-9c83-11e7-8df4-17381322a345.png)

**Comment by ijack9631** [comment]
We are also facing this issue with the plugin not able to parse the dot cover reports , with this error.

**Comment by Evangelink** [comment]
Hi guys,
Thanks for reporting this issue. We will try to have a look at it soon.

**Comment by valhristov** [comment]
Hi @ESolovova, @ijack9631, I am looking at the problem now, but I cannot reproduce it with a simple solution with a class library and unit test project and using the SonarC# 6.4.1 and the latest version of DotCover. I suspect that your command is not correct, because the coverage parser is trying to parse the report homepage and it should not. Could you please, send me the commands that are executed in the build (sonar.scanner.msbuild start, msbuild, dotcover), as well as the complete build output?

**Comment by ijack9631** [comment]
Hi ,
I am trying to import a html report generated from the GUI after an analysis for an IIS application is done using dot cover ,  as analysis report cannot be generated from dot cover console runner for IIS applicatio analysis as per the below issue.
https://youtrack.jetbrains.com/issue/DCVR-5921.

In order to replicate the issue please try the below.
Analyze an IIS Application using dot cover GUI. 
Export the .dvcr file into a html report using the GUI.
Feed in this html report to the sonar dot cover plugin  (It requires html report.).

This should help in replicating the issue. I am trying to do this as there is not direct support command line support.

**Comment by valhristov** [comment]
Hi @ijack9631, thanks for the additional information. I think I was able to import the generated HTML report from the GUI:
- I created a new WebApplication with Visual Studio 2017
- Opened with the dotCover GUI, started it and browsed for a while (manually)
- Created a snapshot and then opened with the GUI and exported to HTML, saved to desktop
- run `SonarQube.Scanner.MSBuild.exe begin /k:webapp1 /d:sonar.cs.dotcover.reportsPaths="C:\Users\Valeri Hristov\Desktop\untitled-0.html"`
- run `msbuild /t:rebuild`
- run `SonarQube.Scanner.MSBuild.exe end`
- opened the SonarQube UI and I was able to see that there is coverage data for the new project.

Am I missing something? I am using dotCover 2017.2.2 and latest SonarSource software (Scanner for MSBuild, SonarC# and SonarQube).

Attached is my report [coverage-report.zip](https://github.com/SonarSource/sonar-csharp/files/1502102/coverage-report.zip)

SonarC# looks for HTML files named with numbers, they are located in the `Untitled-0/src` folder, each file should contain a <script> element with `highlightRanges` method call with some number arrays. If this is not found, no coverage data is imported.
